#!/bin/bash

az login -u $username -p $password -o none
export NAME=cluster
export AZ_GROUP=$(az group list | jq .[0].name | sed 's/"//g')
export AZ_VNET_NAME=$NAME-vnet
export AZ_VNET_ADDR=10.0.0.0/16
export AZ_VNET_SUB_NAME=$NAME-subnet
export AZ_VNET_SUB_ADDR=10.0.0.0/24
export MACH_USER=cloud-user

Bigass
gcloud compute instances create instance-2 --project=t-diagram-366512 --zone=europe-southwest1-a --machine-type=e2-standard-8 --network-interface=network-tier=PREMIUM,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=524737119534-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=instance-2,image=projects/debian-cloud/global/images/debian-11-bullseye-v20220920,mode=rw,size=10,type=projects/t-diagram-366512/zones/us-west4-b/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
gcloud compute instances create instance-bigass --project=t-diagram-366512 --zone=europe-southwest1-a --machine-type=e2-standard-4 --network-interface=network-tier=PREMIUM,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=524737119534-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-11-bullseye-v20220920,mode=rw,size=10,type=projects/t-diagram-366512/zones/us-west4-b/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any --threads-per-core=2


Small bridge
Madrid    ------------------- gcloud compute instances create instance-1 --project=t-diagram-366512 --zone=europe-southwest1-a --machine-type=e2-custom-micro-1024 --network-interface=network-tier=PREMIUM,subnet=default --metadata=ssh-keys=roberto.gonzalezroman:ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAACAQDMO6r\+RrcJJYR1gYMiyQP1HPTfs5FkfZ83RRVSeXTZs7qLN4Zenc52vkz5HcvBEtkPhj1JMz1CcHrSQ/4jZGSt/MqLMvoVd1BwzdZFsR\+EVqq6kt4yEIzKNHdyCAgIkIWxe4m9D8ZNkPOkuATsfpTKO4JdlT3ca9muGVUHAeCYtrPQvXzA8lD5sAYZTp6qmbuhFot4yZCIsjYDXv9W2SoNnK7BUviu0VNblJYQywP27jgicXV/Jh3y17Zq9d\+e0Cv4swTuIHnpP96phFTJRaulESpSCd6S1gzb600X8/uLQ496mK4Qj5dIAFZlxAtn7O8IFO4iK3bYZ175ZQ5q2GHHMVtsIXui3b0RzScUvxcUHR20EEnAzpJtJV7mviUDgucHXV7GcvX\+3Ifttf3DlVZUj9xhMakMInsjCzhhlGgXPddwyA3HVjtBzjXfoJD3\+1q1Q4EsUIRNbf4LRJAMLjVEanL6idZwHsEdbuzL80Z0/0uTkRrnit\+1CaHfrx7aI5EmgzgfZ4dKCbokUi/ETtQV4OKSveEDWvSA4dqReKXQRFGOwJuraKwXH\+Yl1bSbs2BwrmrG1/SldDG9lys6u3La1sqyLZF7I7FvqSiyPtq8KwPBFxcq8h3Y40i3YIg380pMoIH9wvT70ggqZ0ldS573FbQN17V3amiKIX\+O/VAsxQ==\ roberto.gonzalezroman@gruposantander.com --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=524737119534-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-11-bullseye-v20220920,mode=rw,size=10,type=projects/t-diagram-366512/zones/us-west4-b/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
Standard belgica ------------ gcloud compute instances create instance-1 --project=t-diagram-366512 --zone=europe-west1-b --machine-type=e2-custom-micro-1024 --network-interface=network-tier=STANDARD,subnet=default --metadata=ssh-keys=roberto.gonzalezroman:ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAACAQDMO6r\+RrcJJYR1gYMiyQP1HPTfs5FkfZ83RRVSeXTZs7qLN4Zenc52vkz5HcvBEtkPhj1JMz1CcHrSQ/4jZGSt/MqLMvoVd1BwzdZFsR\+EVqq6kt4yEIzKNHdyCAgIkIWxe4m9D8ZNkPOkuATsfpTKO4JdlT3ca9muGVUHAeCYtrPQvXzA8lD5sAYZTp6qmbuhFot4yZCIsjYDXv9W2SoNnK7BUviu0VNblJYQywP27jgicXV/Jh3y17Zq9d\+e0Cv4swTuIHnpP96phFTJRaulESpSCd6S1gzb600X8/uLQ496mK4Qj5dIAFZlxAtn7O8IFO4iK3bYZ175ZQ5q2GHHMVtsIXui3b0RzScUvxcUHR20EEnAzpJtJV7mviUDgucHXV7GcvX\+3Ifttf3DlVZUj9xhMakMInsjCzhhlGgXPddwyA3HVjtBzjXfoJD3\+1q1Q4EsUIRNbf4LRJAMLjVEanL6idZwHsEdbuzL80Z0/0uTkRrnit\+1CaHfrx7aI5EmgzgfZ4dKCbokUi/ETtQV4OKSveEDWvSA4dqReKXQRFGOwJuraKwXH\+Yl1bSbs2BwrmrG1/SldDG9lys6u3La1sqyLZF7I7FvqSiyPtq8KwPBFxcq8h3Y40i3YIg380pMoIH9wvT70ggqZ0ldS573FbQN17V3amiKIX\+O/VAsxQ==\ roberto.gonzalezroman@gruposantander.com --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=524737119534-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-11-bullseye-v20220920,mode=rw,size=10,type=projects/t-diagram-366512/zones/us-west4-b/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
                             

ssh -i ~/.ssh/id_rsa_remote -nNTv -R 0.0.0.0:5905:localhost:5905 roberto.gonzalezroman@34.175.181.55